### ISSUE TITLE
Fairly consistent issue I receive when attempting to use deposit script

### ISSUE THREAD

**Issue by TopDogger1** [0xM14N/rollhelper-extension#2]
It seems that anytime I receive the error "[ROLLHELPER - ERROR] -> Failed to load the steam inventory data - trying again in 3 seconds" The bot is able to auto accept the trade offers, but not able to create another tab which sends the trade automatically. Is there a more consistent way of doing this? It seems to fail 98% of the time.

**Comment by 0xM14N** [comment]
Hey, roll recently changed something on their end. Seems like the persistent query for the inventory endpoint was changed. It was fixed yesterday in lastest update. Should work now.

**Comment by TopDogger1** [comment]
Still having the same problem on latest version, no error in console to go with it so I'm unable to pin it to anything specific.

**Comment by 0xM14N** [comment]
Does it load the inventory now for you? (says how many items loaded instead of error)

**Comment by TopDogger1** [comment]
It does not, it has worked one or two times after I installed the new version but hasn't worked since. 
<img width="92" alt="b0573a034b7777374a2ccfc7bbafc922" src="https://github.com/user-attachments/assets/9ec0486b-b3dc-4d56-a0c0-394453494e52">
